[mcpServers.basecamp]
command = "npx"
args = ["-y", "@aexol-studio/basecamp-to-llm", "mcp"]

  [mcpServers.basecamp.env]
  # Prefer setting these in your shell/OS. You can also inline values here.
  BASECAMP_CLIENT_ID = "${env:BASECAMP_CLIENT_ID}"
  BASECAMP_CLIENT_SECRET = "${env:BASECAMP_CLIENT_SECRET}"
  BASECAMP_REDIRECT_URI = "${env:BASECAMP_REDIRECT_URI}"
  BASECAMP_USER_AGENT = "${env:BASECAMP_USER_AGENT}"

